name: jakob-r
description: R, statistics and photography
author: "Jakob Richter"
avatar-url: https://avatars3.githubusercontent.com/u/1888623?v=3&s=460
footer-links:
  email: blog@jakob-r.de
  github: jakob-r
  instagram: jakob.richter
  flickr: scoobay
  twitter: jak0br
  rss: rss.xml
url: http://jakob-r.github.io
excerpt_separator: <!--more-->
disqus: jakobr
permalink: /:title/

# technical stuff

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
markdown: kramdown
highlighter: rouge
exclude:
  - knit2md
  - _source
sass:
  style: :compressed